app = "attendance-backend"
primary_region = "iad"

[build]
  builder = "paketo/buildpacks:base"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[mounts]
  source = "data"
  destination = "/data"
